<?php
  if( strpos( $_SERVER['SCRIPT_URI'] , '/dev/' ) ){
    $folder = 'dev';
  }
  foreach( $s as $row )
  {
    ?>
      <tr>
        <td><?php echo $row->user_id; ?></td>
        <td><?php echo $row->solution; ?></td>
        <td><?php echo $row->code; ?> <?= $row->nature != '' ? '(Lead Generated By Respicite)' : '' ?> </td>
        <?php 
          $status = $row->status;
        ?>
        <td>
          <?php
            if($status=='Ap')
            {
              echo "Assessment Pending";
            }
            else if($status=='Rp')
            {
                echo "Assessment Completed";
            }
            else
            {
              echo "Report Downloaded";
            }
          ?>
        </td>
        <td>
          <div class="row">
            <div class="col-sm-12">
              <!-- select  -->
              <div class="form-group">
                <?php 
                  if($status=='Ap')
                  {
                    echo "";
                  }
                  else  if($status=='Rp')
                  {
                    ?>
                    <?php 
                      if($row->solution =='OCSS') {
                        ?>
                          <a target='_blank' href="<?php echo 'https://faith-n-hope.com/services/reports/'.base64_encode($row->code)."/".base64_encode($email)."/".base64_encode($row->solution); ?>">View Report</a><br>
                        <?php
                      }
                      else{
                        if( in_array( $row->solution , $allow_solution ) ){
                          // $this->db->where( ['status' => 0 ] );
                          $this->db->order_by('id' , 'DESC');
                          $this->db->where('code' , $row->code);
                          $lastReport =  $this->db->get('report_request')->row_array();
                          // print_r( $lastReport );
                          if( !empty($lastReport) ){
                            if( $lastReport['status'] == 0 || $lastReport['status'] == 2){
                              $time = strtotime(date('Y-m-d H:i:s'));
                              $updateTime = strtotime(date('Y-m-d H:i:s', strtotime( $lastReport['created_date']. ' +45  minutes')));
                              if( $time >= $updateTime ){
                                if( $lastReport['status'] ==  0 ){
                                    $this->db->where([ 'code' => $row->code ]);
                                    $this->db->set([ 'status' => 2 ]);
                                    $this->db->where([ 'id' => $lastReport['id'] ]);
                                    $this->db->update('report_request');
                                }
                                ?>
                                <a <?php if($requestParameter == null) { ?> onclick="window.open(window.location+'/request-generate','_blank');window.open(this.href,'_self');" href="<?php echo base_url().'UserController/create-request/'.$row->code; ?>/<?= $row->solution ?>/<?= $row->user_id ?><?= isset( $folder ) ? '/'.$folder : '' ?>" <?php } else{ ?> onClick="alert('<?= $reportData['report_message'] ?>')" href='#' <?php } ?> >View Report</a><br>
                                <?php
                              }
                              else{
                                  // echo "1-2";
                                  if( $lastReport['code'] != $row->code ){

                                      // echo "1-3";

                                      $where = "code='$row->code' AND status=1";

                                      $this->db->where($where);

                                      $reportStatus =  $this->db->get('report_request');

                                      if( $reportStatus->num_rows() > 0 ){

                                          // echo "1-4";

                                          // echo "1";

                                          $rdata = $reportStatus->row_array();

                                          if( $rdata['status'] == 1 ){

                                              // echo "1-5";

                                            ?>

                                              <a target='_blank' href="<?php echo base_url().'assets/report-pdf/'.$rdata['file_name']; ?>">View Report</a><br>

                                            <?php

                                              if( $reportControl['status'] == 1 ){

                                                  $control = $rdata['mannual_status'] == 1 ? 0 : 1;

                                                  $text =  $rdata['mannual_status'] == 1 ? 'Hide Report' : 'Allow To View';

                                                ?>

                                                  <a href="<?= base_url() ?>UserController/set_mannual_control/<?= $control ?>/<?=$row->code?>/<?= $lastReport['id'] ?>"><?= $text ?></a><br>

                                                <?php

                                              }
                                          }

                                          else{

                                              // echo "1-6";

                                            ?>

                                              <a target='_blank' href='#' onClick="alert('<?= $reportData['report_message'] ?>')" >View Report</a><br>

                                            <?php

                                          }

                                      }

                                      else{

                                          //  echo "1-7";

                                        ?>

                                          <a target='_blank' onclick="alert('<?= $reportData['report_message'] ?>')" >View Report</a><br>

                                        <?php

                                      }

                                  }

                                  else{

                                      //  echo "1-8";

                                    ?>

                                      <a target='_blank' href='#' onClick="alert('<?= $reportData['report_message'] ?>')" >View Report</a><br>

                                    <?php

                                  }

                              }

                            }
                            else{

                                if( !empty($lastReport) ){

                                    if( $lastReport['code'] == $row->code ){

                                        $where = "code='$row->code' AND status = 1";

                                        $this->db->where($where);

                                        $reportStatus =  $this->db->get('report_request');

                                        if( $reportStatus->num_rows() > 0 ){

                                            // echo "1";

                                            $rdata = $reportStatus->row_array();

                                            if( $rdata['status'] == 1 ){

                                                // echo "2-1";

                                              ?>

                                                <a target='_blank' href="<?php echo base_url().'assets/report-pdf/'.$rdata['file_name']; ?>">View Report</a><br>

                                              <?

                                                    if( $reportControl['status'] == 1 ){

                                                        $control = $rdata['mannual_status'] == 1 ? 0 : 1;

                                                        $text =  $rdata['mannual_status'] == 1 ? 'Hide Report' : 'Allow To View';

                                                      ?>

                                                        <a href="<?= base_url() ?>UserController/set_mannual_control/<?= $control ?>/<?=$row->code?>/<?= $lastReport['id'] ?>"><?= $text ?></a><br>

                                                      <?php

                                                    }

                                            }

                                            else{

                                                // echo "2-2";

                                              ?>

                                                <a target='_blank' href='#' onClick="alert('<?= $reportData['report_message'] ?>')" >View Report</a><br>

                                              <?php

                                            }

                                        }

                                        else{

                                            // echo "2-3";

                                          ?>

                                            <a  onclick="alert('<?= $reportData['report_message'] ?>')" >View Report</a><br>

                                          <?php

                                        }

                                    }

                                    else{

                                        // echo "2-4";

                                        ?>

                                        <a <?php if($requestParameter == null)  { ?> onclick="window.open(window.location+'/request-generate','_blank');window.open(this.href,'_self');" href="<?php echo base_url().'UserController/create-request/'.$row->code; ?>/<?= $row->solution ?>/<?= $row->user_id ?><?= isset( $folder ) ? '/'.$folder : '' ?>" <?php } else{ ?> onClick="alert('<?= $reportData['report_message'] ?>')" href='#' <?php } ?> >View Report</a><br>

                                      <?php

                                    }

                                }

                                else{

                                // echo "2-5";

                                  ?>

                                    <a <?php if($requestParameter == null)  { ?> onclick="window.open(window.location+'/request-generate','_blank');window.open(this.href,'_self');" href="<?php echo base_url().'UserController/create-request/'.$row->code; ?>/<?= $row->solution ?>/<?= $row->user_id ?><?= isset( $folder ) ? '/'.$folder : '' ?>" <?php } else{ ?> onClick="alert('<?= $reportData['report_message'] ?>')" href='#' <?php } ?> >View Report</a><br>

                                  <?php
                                }
                            }
                          }
                          else{
                            ?>
                              <a <?php if($requestParameter == null)  { ?> onclick="window.open(window.location+'/request-generate','_blank');window.open(this.href,'_self');" href="<?php echo base_url().'UserController/create-request/'.$row->code; ?>/<?= $row->solution ?>/<?= $row->user_id ?><?= isset( $folder ) ? '/'.$folder : '' ?>" <?php } else{ ?> onClick="alert('<?= $reportData['report_message'] ?>')" href='#' <?php } ?> >View Report</a><br>

                            <?php

                          }
                        }
                        else{

                          ?>
                            <a target='_blank' href="<?php echo base_url().'OtherAjax/download_report.php?code='.base64_encode($row->code); ?>">View Report</a><br>
                          <?php
                        }
                      }
                    ?>
                    <a href="<?php echo base_url().'UserController/Update_Counsellor_remarks/'.base64_encode($row->code); ?>">Counsellor Remarks</a>
                    <?php 
                  }
                  else{
                    ?>
                    <a target='_blank' href="<?php echo base_url().'OtherAjax/download_report.php?code='.base64_encode($row->code); ?>">View Report</a><br>
                    <a href="<?php echo base_url().'UserController/Update_Counsellor_remarks/'.base64_encode($row->code); ?>">Counsellor Remarks</a>
                    <?php 
                  }
                ?>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <?php
  }
?> 